kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/part-of: midlake
    app.kubernetes.io/version: m1
  name: mock-extractor-config
  namespace: {{ .Release.namespace }}
data:
  JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8081
  SERVER_PORT: "8080"
  SERVER_SERVLET_CONTEXT_PATH: /mock-extractor
