kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/part-of: midlake
    app.kubernetes.io/version: m1
  name: postgres-config
  namespace: {{ .Release.namespace }}
data:
  POSTGRES_DB: keycloak
  POSTGRES_PASSWORD: keycloakpwd
  POSTGRES_USER: keycloak

