kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/part-of: midlake
    app.kubernetes.io/version: m1
  name: deploy-token
  namespace: {{ .Release.namespace }}
data:
  .dockerconfigjson: |
    {{ tpl ($.Files.Get "files/back-end/.dockerconfigjson") . | b64enc }}
