kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/part-of: midlake
    app.kubernetes.io/version: m1
  name: keycloak-config
  namespace: {{ .Release.namespace }}
data:
  DB_ADDR: postgres
  DB_DATABASE: keycloak
  DB_PASSWORD: keycloakpwd
  DB_SCHEMA: public
  DB_USER: keycloak
  DB_VENDOR: POSTGRES
  KEYCLOAK_PASSWORD: {{ .Values.keyCloak.password }}
  KEYCLOAK_USER: {{ .Values.keyCloak.username }}
  PROXY_ADDRESS_FORWARDING: "true"
