# Nota: carica il json del realm in un secret, tuttavia attualmente non viene impiegato
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/part-of: midlake
    app.kubernetes.io/version: m1
  name: keycloak-realm-config
  namespace: {{ .Release.namespace }}
data:
  realm.json: {{ tpl ($.Files.Get "files/back-end/keycloak/realm.json") . | b64enc | quote }}
