kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/part-of: midlake
    app.kubernetes.io/version: m1
  name: ld-library-config
  namespace: {{ .Release.namespace }}
data:
  LD_LIBRARY_PATH: {{ .Values.anonymization.hsm.soDirectory }}
