{{- if .Values.decipher.deploy }}
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/part-of: midlake
    app.kubernetes.io/version: m1
  name: decipher-spring-boot-config
  namespace: {{ .Release.namespace }}
data:
  application.properties: {{ tpl ($.Files.Get "files/decipher/application.properties") . | b64enc }}
{{- end }}
