kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/part-of: midlake
    app.kubernetes.io/version: m1
  name: registry-api-config
  namespace: {{ .Release.namespace }}
data:
  NODE_TLS_REJECT_UNAUTHORIZED: "0"
