kind: Secret
type: Opaque
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/part-of: midlake
    app.kubernetes.io/version: m1
  name: registry-api-node-config
  namespace: {{ .Release.namespace }}
data:
  config.json: {{ tpl ($.Files.Get "files/back-end/registry-api/config.json") . | b64enc }}
