# spring
spring:
  main:
    banner-mode: log

# logging
logging:
  file.name: /midlake/logs/midlake-application.log
  pattern:
    console: ""
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%-5p) %-25t{25} %blue(%-45logger{45}) %m%n%wEx"
  level:
    io.github.resilience4j: ERROR
    it.tgi.sazai: DEBUG
    org.springframework.web: INFO

# feign configuration
feign.client.config.default.loggerLevel: FULL

# circuit breaker
resilience4j.circuitbreaker:
  configs:
    default:
      minimumNumberOfCalls: 5
