kind: Secret
type: Opaque
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/part-of: midlake
    app.kubernetes.io/version: m1
  name: central-spring-config
  namespace: {{ .Release.namespace }}
data:
  application-default.yaml: {{ tpl ($.Files.Get "/files/back-end/central/application-default.yaml") . | b64enc }}
